# Generated by Django 4.2.3 on 2023-08-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IQuantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='notreceived',
            name='Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ICost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='IQuantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ISellingprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IName', models.CharField(max_length=100)),
                ('ICost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IQuantitysold', models.PositiveIntegerField()),
                ('received', models.BooleanField(default=False)),
                ('not_received', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sopeoims.order')),
            ],
        ),
    ]
