# Generated by Django 4.2.3 on 2023-08-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0002_order_notreceived_status_alter_inventoryitem_icost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='Order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ICost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='IQuantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ISellingprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
