# Generated by Django 4.2.3 on 2023-08-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0003_inventoryitem_order_alter_inventoryitem_icost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='ICost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='IQuantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ISellingprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
