# Generated by Django 4.2.3 on 2023-08-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0005_alter_inventoryitem_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='IName',
            field=models.CharField(max_length=10),
        ),
    ]
