# Generated by Django 4.2.3 on 2023-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0006_alter_orderitem_iname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='ICost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='IName',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='IQuantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ISellingprice',
            field=models.IntegerField(),
        ),
    ]
