# Generated by Django 4.2.3 on 2023-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0007_alter_inventoryitem_icost_alter_inventoryitem_iname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notreceived',
            name='IIN',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='notreceived',
            name='Status',
            field=models.CharField(default='Pending', max_length=7),
        ),
    ]
