# Generated by Django 4.2.3 on 2023-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0008_alter_notreceived_iin_alter_notreceived_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='IIN',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='IName',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='notreceived',
            name='IIN',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='notreceived',
            name='IName',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='notreceived',
            name='Status',
            field=models.CharField(max_length=7),
        ),
    ]
