# Generated by Django 4.2.3 on 2023-08-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0009_alter_inventoryitem_iin_alter_inventoryitem_iname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotReceived',
        ),
    ]
