# Generated by Django 4.2.3 on 2023-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0010_delete_notreceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IName', models.CharField(max_length=7)),
                ('ICost', models.IntegerField()),
                ('IQuantity', models.IntegerField()),
                ('ISellingprice', models.IntegerField()),
                ('IQuantitysold', models.IntegerField(default=0)),
                ('IProfit', models.IntegerField(blank=True, null=True)),
                ('Revenue', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(max_length=7)),
                ('IIN', models.CharField(max_length=7)),
            ],
        ),
    ]
