# Generated by Django 4.2.3 on 2023-08-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0013_alter_inventoryitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='Order',
            field=models.IntegerField(null=True),
        ),
    ]
