# Generated by Django 4.2.3 on 2023-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0014_alter_inventoryitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IName', models.CharField(max_length=255)),
                ('ICost', models.IntegerField()),
                ('Order', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
