# Generated by Django 4.2.3 on 2023-08-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0015_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='IIN',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
