# Generated by Django 4.2.3 on 2023-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0018_delete_all_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.CharField(blank=True, max_length=7, unique=True)),
                ('IName', models.CharField(max_length=255)),
                ('ICost', models.IntegerField()),
                ('Order', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
