# Generated by Django 4.2.3 on 2023-08-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0019_all_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Transaction',
        ),
    ]
