# Generated by Django 4.2.3 on 2023-08-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0021_all_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_transaction', to='sopeoims.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CanceledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_transaction', to='sopeoims.transaction')),
            ],
        ),
    ]
