# Generated by Django 4.2.3 on 2023-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0023_remove_receivedtransaction_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canceled_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.CharField(blank=True, max_length=7, unique=True)),
                ('IName', models.CharField(max_length=255)),
                ('ICost', models.IntegerField()),
                ('Order', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Received_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IIN', models.CharField(blank=True, max_length=7, unique=True)),
                ('IName', models.CharField(max_length=255)),
                ('ICost', models.IntegerField()),
                ('Order', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
