# Generated by Django 4.2.3 on 2023-08-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0024_canceled_transaction_received_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceled_transaction',
            name='IIN',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='received_transaction',
            name='IIN',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
