# Generated by Django 4.2.3 on 2023-08-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sopeoims', '0026_panding_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panding_Transaction',
        ),
    ]
